apiVersion: v1
kind: Service
metadata:
 name: magento2
 labels:
  app: magento2
spec:
 ports:
  - port: 80
 selector:
  app: magento2
  tier: frontend
 type: LoadBalancer #any service of type NodePort can be accessed over that IP address


