apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: magento2
 labels:
  app: magento2
spec:
 selector:
  matchLabels:
   app: magento2
   tier: frontend
 strategy:
  type: Recreate
 template:
  metadata:
   labels:
    app: magento2
    tier: frontend
  spec:
   containers:
    -image: alexcheng/magento #https://hub.docker.com/r/alexcheng/ma...
    name: magento2
    env:
    -name: MAGENTO_DB_HOST
     value: magento2-mysql
    -name: MAGENTO_DB_PASSWORD
     valueFrom:
      secretKeyRef:
       name: mysql-pass
       key: password
    ports:
    -containerPort: 80
     name: magento2
